networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  master:
    volumes:
     - ./config:/test/config
     - ${BIN_SRC_PATH}:${BIN_DST_PATH}
    image: ${IMAGE}
    command: redis-server /test/config/master.conf
    ports:
      - "30692:6379"
  slave:
    volumes:
     - ./config:/test/config
     - ${BIN_SRC_PATH}:${BIN_DST_PATH}
    image: ${IMAGE}
    command: redis-server /test/config/slave.conf
    ports:
      - "30693:6379"
  sentinel1:
    volumes:
     - ./config:/test/config
     - ${BIN_SRC_PATH}:${BIN_DST_PATH}
    image: ${IMAGE}
    command: redis-server /test/config/sentinel1.conf --sentinel
    ports:
      - "30664:26379"
  sentinel2:
    volumes:
      - ./config:/test/config
      - ${BIN_SRC_PATH}:${BIN_DST_PATH}
    image: ${IMAGE}
    command: redis-server /test/config/sentinel2.conf --sentinel
    ports:
      - "30665:26379"
  sentinel3:
    volumes:
      - ./config:/test/config
      - ${BIN_SRC_PATH}:${BIN_DST_PATH}
    image: ${IMAGE}
    command: redis-server /test/config/sentinel3.conf --sentinel
    ports:
      - "30666:26379"
  instance_standby:
    volumes:
      - ./config:/test/config
      - ${BIN_SRC_PATH}:${BIN_DST_PATH}
    image: ${IMAGE}
    command: bash -c "while true; do sleep 2; done"
    ports:
      - "30667:26379"
      - "30668:6379"